username: ghalymbryan@gmail.com
password: 98987768474400Bg$!
phone_number: 3856020604

positions:
- General Ledger Accountant
- Senior Accountant
- Accountant

locations:
- Orange County, California
- Salt Lake County, Utah 

# --------- Optional Parameters -------
# uploads:
#  Resume: # PATH TO Resume 
#  Cover Letter: # PATH TO cover letter
#  Photo: # PATH TO photo


# output_filename:
# - # PATH TO OUTPUT FILE (default output.csv)

# blacklist:
# - # Company names you want to ignore

#blackListTitles:
#- # Add job titles you want to ignore
Fund Accountant
Non-profit Accountant
Staff Accountant
Bookkeeper
Accounts Receivable
Accounts Payable
